search_task:
  description: >
    오늘 AI타임스의 주요 뉴스 리스트 추출하기
  expected_output: >
    오늘 AI타임스의 주요 뉴스 리스트를 추출하기.
  agent: researcher

write_task:
  description: >
    주어진 뉴스 정보들을 바탕으로 주요 뉴스를 요약하여 정리하기
  expected_output: >
    오늘의 주요 뉴스의 제목과 내용은 중요한 내용을 요약해서 정리하기
  agent: editor
  context:
    - search_task